// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwlatgborndxwkqnareb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3bGF0Z2Jvcm5keHdrcW5hcmViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODAyNDIsImV4cCI6MjA2MTg1NjI0Mn0.NY0dmevoU1Ib2ekQlJ7za1e_S_lUdgHdicUaE_KGhcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);